//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIndowsFormsUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YourName")]
        public string playerName {
            get {
                return ((string)(this["playerName"]));
            }
            set {
                this["playerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::ArtificialIntelligence.GameLevel level {
            get {
                return ((global::ArtificialIntelligence.GameLevel)(this["level"]));
            }
            set {
                this["level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classic")]
        public global::WIndowsFormsUI.Forms.CardDeckType deckType {
            get {
                return ((global::WIndowsFormsUI.Forms.CardDeckType)(this["deckType"]));
            }
            set {
                this["deckType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::WIndowsFormsUI.Forms.CardBackType cardBack {
            get {
                return ((global::WIndowsFormsUI.Forms.CardBackType)(this["cardBack"]));
            }
            set {
                this["cardBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sound {
            get {
                return ((bool)(this["sound"]));
            }
            set {
                this["sound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool notifications {
            get {
                return ((bool)(this["notifications"]));
            }
            set {
                this["notifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int character {
            get {
                return ((int)(this["character"]));
            }
            set {
                this["character"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalGamesVersusEasy {
            get {
                return ((int)(this["totalGamesVersusEasy"]));
            }
            set {
                this["totalGamesVersusEasy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalWinsVersusEasy {
            get {
                return ((int)(this["totalWinsVersusEasy"]));
            }
            set {
                this["totalWinsVersusEasy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalGamesVersusNormal {
            get {
                return ((int)(this["totalGamesVersusNormal"]));
            }
            set {
                this["totalGamesVersusNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalWinsVersusNormal {
            get {
                return ((int)(this["totalWinsVersusNormal"]));
            }
            set {
                this["totalWinsVersusNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalGamesVersusHard {
            get {
                return ((int)(this["totalGamesVersusHard"]));
            }
            set {
                this["totalGamesVersusHard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalWinsVersusHard {
            get {
                return ((int)(this["totalWinsVersusHard"]));
            }
            set {
                this["totalWinsVersusHard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalRoundWinsVsEasy {
            get {
                return ((int)(this["totalRoundWinsVsEasy"]));
            }
            set {
                this["totalRoundWinsVsEasy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalRoundLossesVsEasy {
            get {
                return ((int)(this["totalRoundLossesVsEasy"]));
            }
            set {
                this["totalRoundLossesVsEasy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalRoundWinsVsNormal {
            get {
                return ((int)(this["totalRoundWinsVsNormal"]));
            }
            set {
                this["totalRoundWinsVsNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalRoundLossesVsNormal {
            get {
                return ((int)(this["totalRoundLossesVsNormal"]));
            }
            set {
                this["totalRoundLossesVsNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalRoundWinsVsHard {
            get {
                return ((int)(this["totalRoundWinsVsHard"]));
            }
            set {
                this["totalRoundWinsVsHard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalRoundLossesVsHard {
            get {
                return ((int)(this["totalRoundLossesVsHard"]));
            }
            set {
                this["totalRoundLossesVsHard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10/13/2016 19:26:00")]
        public global::System.DateTime lastUpdate {
            get {
                return ((global::System.DateTime)(this["lastUpdate"]));
            }
            set {
                this["lastUpdate"] = value;
            }
        }
    }
}
